apiVersion: v1
kind: Service
metadata:
  name: soumik-express-svc2
spec:
  type: NodePort
  selector:
    app: simple-express-app2
  ports:
    - port: 80
      targetPort: 8080
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-express-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-express-app2
  template:
    metadata:
      labels:
        app: simple-express-app2
    spec:
      containers:
        - name: simple-express-app2
          image: msoumik78/simple-express-app2
          ports:
            - containerPort: 8080