apiVersion: v1
kind: Service
metadata:
  name: soumik-express-svc
spec:
  selector:
    app: simple-express-app
  ports:
    - port: 80
      targetPort: 4200
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-express-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-express-app
  template:
    metadata:
      labels:
        app: simple-express-app
    spec:
      imagePullSecrets:
      - name: do-registry       
      containers:
        - name: simple-express-app
          image: registry.digitalocean.com/auto-trader-registry/express-app-soumik
          imagePullPolicy: Always  
          ports:
            - containerPort: 4200